---
title: "Tokyo"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(leaflet)
library(htmltools)
```

Possible points
Bottom
(35.634806, 139.647121)

Top
(35.748292, 139.838695)

```{r}
# long lat
bottom <- c(139.647, 35.634)
top <- c(139.84, 35.70)
boundary <- array(c(bottom, top))

#boundary = array(c(139.647121, 35.634806, 139.838695, 35.748292))

locations <- read.csv(textConnection(
  "Name,Lat,Long,LoveYou
Shinjuku Station,35.690524,139.699583,1
Yoyogi Park,35.671847,139.694894,1
Shibuya Crossing,35.659523,139.700503,1
Meguro River,35.616648,139.749991,1
Ueno Park,35.714358,139.773596,2
Odaiba,35.624641,139.776464,1
Akihabara,35.699084,139.770826,2
"))

assist <- colorFactor(c("green", "red"), domain=c(1,2))
```

```{r}
m <- leaflet(locations)  %>% addTiles() %>% addProviderTiles(providers$CartoDB.Positron) %>% fitBounds(boundary[1], boundary[2], boundary[3], boundary[4]) %>% addCircleMarkers(~Long, ~Lat, label=~htmlEscape(Name), radius=7, color= ~assist(LoveYou), stroke=FALSE, fillOpacity=0.5)

m
```


